services:
  server:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx:alpine
    container_name: webapp-server-1
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./php:/var/www/php
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: webapp-php-1
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: unless-stopped
    volumes:
     - ./src:/var/www/html
     - ./php:/var/www/php
    environment:
      - DB_HOST=database # The name of the service below
      - DB_NAME=myapp
      - DB_USER=user
      - DB_PASS=${USER_DB_PASSWORD}

  database:
    image: mysql:8.0
    container_name: webapp-database-1
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d:ro 
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DB_PASSWORD}
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${USER_DB_PASSWORD}

volumes:
  init-db:
  db_data:
  web_static: 