services:
  server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - web_server:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
    environment:
      - DB_HOST=database # The name of the service below
      - DB_NAME=myapp
      - DB_USER=user
      - DB_PASS=${USER_DB_PASSWORD}

  database:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DB_PASSWORD}
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${USER_DB_PASSWORD}

volumes:
  db_data:
  web_server: 
