services:
  server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./php:/var/www/php
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/php
      - ./src:/var/www/html
    environment:
      - DB_HOST=database # The name of the service below
      - DB_NAME=myapp
      - DB_USER=user
      - DB_PASS=${USER_DB_PASSWORD}

  database:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d 
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DB_PASSWORD}
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${USER_DB_PASSWORD}

volumes:
  init-db:
  db_data:
  web_server: 
